name: Update Builds JSON

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type (IOS_SIMULATOR_DEV, IOS_PHYSICAL_DEV, or ANDROID_DEV)"
        required: true
        type: string
      id:
        description: "Build ID"
        required: true
        type: string
      version:
        description: "Build version"
        required: true
        type: string
      timestamp:
        description: "Build timestamp (milliseconds since epoch)"
        required: true
        type: number
      url:
        description: "Download URL"
        required: true
        type: string
      buildNumber:
        description: "Build number"
        required: true
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Update builds.json
        run: |
          node -e '
            const fs = require("fs");
            const buildType = "${{ github.event.inputs.buildType }}";
            
            // Validate build type
            if (!["IOS_SIMULATOR_DEV", "IOS_PHYSICAL_DEV", "ANDROID_DEV"].includes(buildType)) {
              console.error("Invalid build type:", buildType);
              process.exit(1);
            }

            // Create new build entry
            const newBuild = {
              id: "${{ github.event.inputs.id }}",
              version: "${{ github.event.inputs.version }}",
              timestamp: ${{ github.event.inputs.timestamp }},
              url: "${{ github.event.inputs.url }}",
              buildNumber: "${{ github.event.inputs.buildNumber }}"
            };

            // Read and update builds.json
            const builds = JSON.parse(fs.readFileSync("builds.json", "utf8"));
            builds[buildType].builds.unshift(newBuild);
            
            // Write back to file
            fs.writeFileSync("builds.json", JSON.stringify(builds, null, 2));
          '

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add builds.json
          git commit -m "Update builds.json with new ${{ github.event.inputs.buildType }} build"
          git push origin main
